[package]
name = "fractal-space"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = "0.32.0"
serde = { version = "1.0", features = ["derive", "rc"] }
num = "0.4.0"
